name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/nextjs-cicd-test
            npm ci
            npm run build
            /www/server/nodejs/v22.15.1/bin/pm2 restart nextjs-cicd
