name: 🚀 Deploy Next.js App

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: string
      use_npm_ci:
        description: 'Run npm ci (clean install)'
        required: true
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/nextjs-cicd-test
            echo "Deploying branch: ${{ github.event.inputs.branch }}"
            git fetch origin
            git checkout ${{ github.event.inputs.branch }}
            git pull origin ${{ github.event.inputs.branch }}
            echo "Starting deployment"
            if [ "${{ github.event.inputs.use_npm_ci }}" = "true" ]; then
                echo "Running npm ci..."
                npm ci
            fi
            echo "Building application..."
            npm run build
            echo "Restarting PM2 process..."
            /www/server/nodejs/v22.15.1/bin/pm2 restart nextjs-cicd
            echo "Deployment completed successfully!"
