name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/nextjs-cicd-test
            source ~/.bashrc  # Load environment variables
            export PATH=$PATH:/www/server/nodejs/v22.15.1/bin  # Add pm2 to PATH
            npm i
            npm run build
            /www/server/nodejs/v22.15.1/bin/pm2 restart nextjs-cicd  # Use full path to pm2
