name: Deploy to Ubuntu Server

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Deployment name/description'
        required: true
        type: string
        default: 'Manual deployment'
      use_npm_ci:
        description: 'Run npm ci (clean install)'
        required: true
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy - ${{ github.event.inputs.name || 'Production' }}
    outputs:
      run-name: ${{ steps.set-run-name.outputs.run-name }}
    steps:
      - name: Set run name
        id: set-run-name
        run: |
          echo "run-name=Deploy - ${{ github.event.inputs.name || 'Production' }}" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/nextjs-cicd-test            
            echo "Starting deployment: ${{ github.event.inputs.name }}"
            if ${{ github.event.inputs.use_npm_ci == 'true' }};
                npm ci
            fi
            npm run build
            /www/server/nodejs/v22.15.1/bin/pm2 restart nextjs-cicd
